# NumPy

Multidimensional array library.

In [2]:
import numpy as np

In [3]:
#initialize an array
arr = np.array([1,2,3])

#show
arr

array([1, 2, 3])

In [4]:
# two or more dimensional arrays
ar = np.array([[3,6,9,12,15,18,21],
               [2,9,8,5,5,6,7],
              [1,2,3,4,5,6,7]])

print(ar)

[[ 3  6  9 12 15 18 21]
 [ 2  9  8  5  5  6  7]
 [ 1  2  3  4  5  6  7]]


In [5]:
#getting dimesional
ar.ndim

2

In [6]:
#Return the shape of an array.
ar.shape
#2 rows, 3 columns

#another usage
# np.shape(ar)

(3, 7)

In [7]:
#data type
ar.dtype

dtype('int32')

In [8]:
#specify the dtype
sp =np.array([1,5,7], dtype='int8')

sp.dtype

dtype('int8')

In [9]:
#Length of one array element in bytes.
print(ar.itemsize)

print(sp.itemsize)

4
1


In [10]:
#Number of elements in the array
ar.size

21

In [11]:
#Total bytes consumed by the elements of the array
ar.nbytes

84

In [12]:
#Get a specific element fron an array
ar[1,2]

#You can use negative index
# ar[1,-1]

#get everything
# ar[:]

8

In [13]:
#get a specific row
ar[1,:]

array([2, 9, 8, 5, 5, 6, 7])

In [14]:
#get a specific column
ar[:,1]

array([6, 9, 2])

In [15]:
#get a specific interval --- in [::x] x is stepsize 
ar[0:3, 1:6:2]

array([[ 6, 12, 18],
       [ 9,  5,  6],
       [ 2,  4,  6]])

In [16]:
#Change a value
ar[1,6] = 11

ar

array([[ 3,  6,  9, 12, 15, 18, 21],
       [ 2,  9,  8,  5,  5,  6, 11],
       [ 1,  2,  3,  4,  5,  6,  7]])

In [17]:
#Change values
ar[0:2,1::2] = 11
ar

array([[ 3, 11,  9, 11, 15, 11, 21],
       [ 2, 11,  8, 11,  5, 11, 11],
       [ 1,  2,  3,  4,  5,  6,  7]])

In [18]:
#Lets create a new array
n = np.array([[[1,2,3],[4,5,6]],
             [[7,8,9],[10,11,12]]])

print(n)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
n[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [20]:
n[0,1]

array([4, 5, 6])

In [21]:
n[0,0:2:2]

array([[1, 2, 3]])

In [22]:
n[1,0,1]

8

In [23]:
#Return a new array of given shape and type, filled with zeros
np.zeros((3,2), dtype='int8')

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

In [24]:
#Return a new array of given shape and type, filled with ones
np.ones((1,2,3,4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [25]:
#Return a new array of given shape and type, filled with numbers you want
np.full((6,3), 6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [26]:
#Return a full array with the same shape and type as a given array
np.full_like(n,11)

array([[[11, 11, 11],
        [11, 11, 11]],

       [[11, 11, 11],
        [11, 11, 11]]])

In [27]:
# Random values in a given shape.
np.random.rand(2,2)

array([[0.29181173, 0.53115696],
       [0.86166127, 0.80219633]])

In [28]:
#Random integer values between 2 and 6
np.random.randint(2,6, size=(2,3))

array([[2, 3, 3],
       [2, 5, 2]])

In [29]:
#Return the identity array.
#The identity array is a square array with ones on the main diagonal.
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
#Repeat elements of an array.
a = np.array([[3,6,9]])
np.repeat(a,3, axis=0)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [31]:
np.repeat(a,3, axis=1)

array([[3, 3, 3, 6, 6, 6, 9, 9, 9]])

#### Copying arrays !

In [32]:
a =np.array([1,2,3,4])

#b = a 

#When you did like this you create a referans
#That means if you change something in b, it also changes in a.

#To make copy
b = a.copy()
b

array([1, 2, 3, 4])

In [34]:
#you can use math operators with arrays.(+,-,*,/,**,cos, etc.)
a ** 2
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [40]:
ar = np.ones((2,3))
print(ar)

br = np.full((3,2),6)
print(br)

#Matrix product of two arrays
np.matmul(ar,br)

[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6]
 [6 6]
 [6 6]]


array([[18., 18.],
       [18., 18.]])

In [43]:
#Compute the determinant of an array
np.linalg.det(np.identity(3))

1.0

### Statistics 

In [46]:
ar = np.array([[3,6,9,12,15,18,21],
               [2,9,8,5,5,6,7],
              [1,2,3,4,5,6,7]])

In [50]:
# min value
np.min(ar)

1

In [51]:
#max value
np.max(ar)

array([21,  9,  7])

In [55]:
#Reshaping arrays
print(ar.shape)

ar.reshape((7,3))

(3, 7)


array([[ 3,  6,  9],
       [12, 15, 18],
       [21,  2,  9],
       [ 8,  5,  5],
       [ 6,  7,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [59]:
#Stack arrays in sequence vertically (row wise)
a = np.array([1,2,3])
b= np.array([3,6,9])

np.vstack([a,b])

array([[1, 2, 3],
       [3, 6, 9]])

In [62]:
#Stack arrays in sequence horizontally
np.hstack([a,b])

array([1, 2, 3, 3, 6, 9])

In [71]:
#Load data from a text file, with missing values handled as specified
data = np.genfromtxt('file.txt', delimiter=',')
data.astype('int32')

array([[  1,   2,   8,   6,  54,  58,  89,  53,   9],
       [ 21,  52,   5,   5,   3,   3, 564,  22,   1],
       [564,   5,  58, 332,  18,  56,   8,   0,   1],
       [655,  56,  92,  78,   9,  63,   3,  46,  14]])

In [72]:
data > 90

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True, False, False],
       [ True, False, False,  True, False, False, False, False, False],
       [ True, False,  True, False, False, False, False, False, False]])

In [77]:
data[data>90]

array([564., 564., 332., 655.,  92.])

In [83]:
#Test whether all array elements along a given axis evaluate to True
np.all((data > 90) & (data < 300), axis=0)

array([False, False, False, False, False, False, False, False, False])

In [100]:
#Return evenly spaced values within a given interval.(start,stop,step,dtype)
np.arange(10,20,2.6,dtype='float64')

array([10. , 12.6, 15.2, 17.8])

In [104]:
#Return evenly spaced numbers over a specified interval.
a = np.linspace(0,10,10,dtype='int32',retstep=True)
a

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10]), 1.1111111111111112)

In [111]:
#Return a contiguous flattened array. 1-D
np.ravel(ar)

array([ 3,  6,  9, 12, 15, 18, 21,  2,  9,  8,  5,  5,  6,  7,  1,  2,  3,
        4,  5,  6,  7])

In [109]:
#Return a copy of the array collapsed into one dimension.
ar.flatten()

array([ 3,  6,  9, 12, 15, 18, 21,  2,  9,  8,  5,  5,  6,  7,  1,  2,  3,
        4,  5,  6,  7])

In [134]:
#Set printing options.
#These options determine the way floating point numbers, arrays and other NumPy objects are displayed

np.set_printoptions(threshold=5,edgeitems=2) 
ar

array([[ 3,  6, ..., 18, 21],
       [ 2,  9, ...,  6,  7],
       [ 1,  2, ...,  6,  7]])

In [132]:
#Return a 2-D array with ones on the diagonal and zeros elsewhere
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [136]:
#Return a new array of given shape and type, without initializing entries
np.empty((3,4),dtype='int32')

array([[ 3,  6, 18, 21],
       [ 2,  9,  6,  7],
       [ 1,  2,  6,  7]])